name: Deploy para GitHub Pages

on:
  push:
    branches:
      - master  # Altere se seu branch principal for outro

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar e rodar o build
        run: |
          npm install
          npm run build

      - name: Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
